baseURL = "http://atlantis.run"
languageCode = "en-us"
title = "Atlantis - A unified workflow for collaborating on Terraform through GitHub and GitLab"
theme = "kube"
description = "A unified workflow for collaborating on Terraform through GitHub and GitLab"
Paginate = 4
[[menu.main]]
    name = "Docs"
    weight = -100
    url = "https://github.com/runatlantis/atlantis#getting-started"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "FAQ"
    weight = -100
    url = "https://github.com/runatlantis/atlantis#faq"
[[menu.main]]
    name = "Demo"
    weight = 100
    url = "https://www.youtube.com/watch?v=TmIPWda0IKg"
