version: 2
jobs:
  build:
    working_directory: /go/src/github.com/runatlantis/atlantis
    docker:
      - image: circleci/golang:1.10
        environment:
          TERRAFORM_VERSION: 0.11.4
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run: make test-coverage
      - run: make check-fmt
      - run: make check-gometalint
      - run:
          name: post coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
      - run: make build-service
      # We don't run e2e tests on fork PRs because they don't have access to the secret env vars.
      - run: if [ -z "${CIRCLE_PR_REPONAME}" ]; then ./scripts/e2e.sh; fi
      - run:
          name: Build image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t runatlantis/atlantis:latest .
            fi
      - run:
          name: Push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
              docker push runatlantis/atlantis:latest
            fi
      - run:
          name: Tag and push version if exists
          # work around until tags are properly supported
          # https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/6
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              for TAG in $(git tag --contains $CIRCLE_SHA1); do
                docker tag runatlantis/atlantis:latest runatlantis/atlantis:$TAG
                docker push runatlantis/atlantis:$TAG
              done
            fi
